# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enterdata.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import os
import csv

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_enterinfowindow(object):

    def okay(self):
        
        fngot = self.enterfname.text()
        lngot = self.enterlnam.text()
        idgot = self.enterid.text()
        codegot = self.entercode.text()
        
        statgot = self.enterstatus.text()
        if(fngot == ''):
            self.nofname.setText('<p style=\"color:red\";>Enter First Name</p>')
        if(lngot == ''):
            self.nolname.setText('<p style=\"color:red\";>Enter Last Name</p>')
        if(idgot == ''):
            self.noid.setText('<p style=\"color:red\";>Enter Id</p>')
        if(codegot == ''):
            self.nocode.setText('<p style=\"color:red\";>Enter Code</p>')
        if(statgot == ''):
            self.nostatus.setText('<p style=\"color:red\";>Enter Status</p>')
        else:
            #print(fngot + lngot + idgot)
            print(lngot)
            print(idgot)
            print(codegot)
            print(statgot)
            for file in os.listdir('dataSet'):
                word = file.split('.')
                lastface = 0
                if(lastface < int(word[1])):
                    lastface = int(word[1])
            with open('peopledata.csv','a', newline = '') as fp:
                    writer = csv.writer(fp)
                    entries = [lastface,idgot,fngot,lngot,codegot,'m',statgot]
                    writer.writerow(entries)
    
    def setupUi(self, enterinfowindow):
        enterinfowindow.setObjectName(_fromUtf8("enterinfowindow"))
        enterinfowindow.resize(677, 292)
        enterinfowindow.setMinimumSize(QtCore.QSize(677, 292))
        enterinfowindow.setMaximumSize(QtCore.QSize(677, 292))
        enterinfowindow.setStyleSheet(_fromUtf8(""))
        self.f_namelabl = QtGui.QLabel(enterinfowindow)
        self.f_namelabl.setGeometry(QtCore.QRect(260, 10, 120, 30))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.f_namelabl.setFont(font)
        self.f_namelabl.setObjectName(_fromUtf8("f_namelabl"))
        self.l_namelabl = QtGui.QLabel(enterinfowindow)
        self.l_namelabl.setGeometry(QtCore.QRect(260, 50, 120, 30))
        self.l_namelabl.setObjectName(_fromUtf8("l_namelabl"))
        self.idlabl = QtGui.QLabel(enterinfowindow)
        self.idlabl.setGeometry(QtCore.QRect(260, 90, 120, 30))
        self.idlabl.setObjectName(_fromUtf8("idlabl"))
        self.codelabl = QtGui.QLabel(enterinfowindow)
        self.codelabl.setGeometry(QtCore.QRect(260, 130, 120, 30))
        self.codelabl.setObjectName(_fromUtf8("codelabl"))
        self.label_5 = QtGui.QLabel(enterinfowindow)
        self.label_5.setGeometry(QtCore.QRect(260, 170, 120, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.statuslabl = QtGui.QLabel(enterinfowindow)
        self.statuslabl.setGeometry(QtCore.QRect(260, 210, 120, 30))
        self.statuslabl.setObjectName(_fromUtf8("statuslabl"))
        self.maleradio = QtGui.QRadioButton(enterinfowindow)
        self.maleradio.setGeometry(QtCore.QRect(370, 170, 120, 30))
        self.maleradio.setObjectName(_fromUtf8("maleradio"))
        self.femaleradio = QtGui.QRadioButton(enterinfowindow)
        self.femaleradio.setGeometry(QtCore.QRect(480, 170, 120, 30))
        self.femaleradio.setObjectName(_fromUtf8("femaleradio"))
        self.otherradio = QtGui.QRadioButton(enterinfowindow)
        self.otherradio.setGeometry(QtCore.QRect(580, 170, 120, 30))
        self.otherradio.setObjectName(_fromUtf8("otherradio"))
        self.enterfname = QtGui.QLineEdit(enterinfowindow)
        self.enterfname.setGeometry(QtCore.QRect(370, 10, 281, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 227, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 100, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 133, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 180, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 227, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 227, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 100, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 133, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 180, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 227, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 100, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 227, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 100, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 133, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 100, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 100, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 180, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 200, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.enterfname.setPalette(palette)
        self.enterfname.setObjectName(_fromUtf8("enterfname"))
        self.enterlnam = QtGui.QLineEdit(enterinfowindow)
        self.enterlnam.setGeometry(QtCore.QRect(370, 50, 281, 20))
        self.enterlnam.setObjectName(_fromUtf8("enterlnam"))
        self.enterid = QtGui.QLineEdit(enterinfowindow)
        self.enterid.setGeometry(QtCore.QRect(370, 90, 281, 20))
        self.enterid.setObjectName(_fromUtf8("enterid"))
        self.entercode = QtGui.QLineEdit(enterinfowindow)
        self.entercode.setGeometry(QtCore.QRect(370, 130, 281, 20))
        self.entercode.setObjectName(_fromUtf8("entercode"))
        self.enterstatus = QtGui.QLineEdit(enterinfowindow)
        self.enterstatus.setGeometry(QtCore.QRect(370, 210, 281, 20))
        self.enterstatus.setObjectName(_fromUtf8("enterstatus"))
        self.okbutton = QtGui.QPushButton(enterinfowindow)
        self.okbutton.setGeometry(QtCore.QRect(420, 255, 100, 25))
        self.okbutton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.okbutton.setFont(font)
        self.okbutton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.okbutton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.okbutton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.okbutton.setStyleSheet(_fromUtf8("background-color: rgb(113, 184, 185);"))
        self.okbutton.setObjectName(_fromUtf8("okbutton"))
        self.cancelbutton = QtGui.QPushButton(enterinfowindow)
        self.cancelbutton.setGeometry(QtCore.QRect(550, 255, 100, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelbutton.setFont(font)
        self.cancelbutton.setStyleSheet(_fromUtf8("background-color: rgb(113, 184, 185);"))
        self.cancelbutton.setObjectName(_fromUtf8("cancelbutton"))
        self.line = QtGui.QFrame(enterinfowindow)
        self.line.setGeometry(QtCore.QRect(240, 5, 20, 280))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(enterinfowindow)
        self.line_2.setGeometry(QtCore.QRect(660, 5, 10, 280))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(enterinfowindow)
        self.line_3.setGeometry(QtCore.QRect(250, 230, 411, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.nofname = QtGui.QLabel(enterinfowindow)
        self.nofname.setGeometry(QtCore.QRect(540, 10, 100, 20))
        self.nofname.setText(_fromUtf8(""))
        self.nofname.setObjectName(_fromUtf8("nofname"))
        self.nolname = QtGui.QLabel(enterinfowindow)
        self.nolname.setGeometry(QtCore.QRect(540, 50, 100, 20))
        self.nolname.setText(_fromUtf8(""))
        self.nolname.setObjectName(_fromUtf8("nolname"))
        self.noid = QtGui.QLabel(enterinfowindow)
        self.noid.setGeometry(QtCore.QRect(540, 90, 100, 20))
        self.noid.setText(_fromUtf8(""))
        self.noid.setObjectName(_fromUtf8("noid"))
        self.nocode = QtGui.QLabel(enterinfowindow)
        self.nocode.setGeometry(QtCore.QRect(540, 130, 100, 20))
        self.nocode.setText(_fromUtf8(""))
        self.nocode.setObjectName(_fromUtf8("nocode"))
        self.nostatus = QtGui.QLabel(enterinfowindow)
        self.nostatus.setGeometry(QtCore.QRect(540, 210, 100, 20))
        self.nostatus.setText(_fromUtf8(""))
        self.nostatus.setObjectName(_fromUtf8("nostatus"))
        self.imagedisplay = QtGui.QLabel(enterinfowindow)
        self.imagedisplay.setGeometry(QtCore.QRect(20, 22, 211, 211))
        self.imagedisplay.setText(_fromUtf8(""))
        self.imagedisplay.setObjectName(_fromUtf8("imagedisplay"))

        self.retranslateUi(enterinfowindow)
        QtCore.QMetaObject.connectSlotsByName(enterinfowindow)

    
            

    def setphoto(self,enterinfowindow):
        lastface = 0
        for file in os.listdir('dataSet'):
            #print(maxid)
            word = file.split('.')
            
            if(lastface < int(word[1])):
                lastface = int(word[1])
                print(lastface)
        img = 'dataSet/User.'+str(lastface)+'.1.jpg'
        print('photoset')
        
        self.imagedisplay.setPixmap(QtGui.QPixmap(_fromUtf8(img)))
        self.imagedisplay.setScaledContents(False)

    def cancel(self):
        print('asd')
        sys.exit()

    def retranslateUi(self, enterinfowindow):
        enterinfowindow.setWindowTitle(_translate("enterinfowindow", "Enter Information", None))
        self.f_namelabl.setText(_translate("enterinfowindow", "First Name      :", None))
        self.l_namelabl.setText(_translate("enterinfowindow", "Last Name       :", None))
        self.idlabl.setText(_translate("enterinfowindow", "ID no.              :", None))
        self.codelabl.setText(_translate("enterinfowindow", "Code                :", None))
        self.label_5.setText(_translate("enterinfowindow", "Sex                  :", None))
        self.statuslabl.setText(_translate("enterinfowindow", "Status              : ", None))
        self.maleradio.setText(_translate("enterinfowindow", "Male", None))
        self.femaleradio.setText(_translate("enterinfowindow", "Female", None))
        self.otherradio.setText(_translate("enterinfowindow", "Any Other", None))
        self.okbutton.setText(_translate("enterinfowindow", "Ok", None))
        
        self.okbutton.clicked.connect(self.okay)
        self.cancelbutton.setText(_translate("enterinfowindow", "Cancel", None))
        self.cancelbutton.clicked.connect(self.cancel)
        
        Ui_enterinfowindow.setphoto(self,enterinfowindow)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    enterinfowindow = QtGui.QWidget()
    ui = Ui_enterinfowindow()
    ui.setupUi(enterinfowindow)
    enterinfowindow.show()
    sys.exit(app.exec_())

